version: 2
machine:
  pre:
    - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
  services:
    - docker
  java:
    version: oraclejdk8

dependencies:
  pre:
    - docker info
    - mvn dependency:resolve
    - mvn clean package
    - mvn integration-test
    - docker build --rm=false -t lprates/sbdocker .

test:
  post:
    - docker run -d -p 8080:8080 -t lprates/sbdocker;  sleep 10
    - curl --retry 10 --retry-delay 5 -v http://localhost:8080

deployment:
  hub:
    branch: [sb-docker-circleci-example]
    commands:
      - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      - docker tag lprates/sbdocker $DOCKER_HUB_USER_ID/sbdocker:$CIRCLE_SHA1
      - docker tag lprates/sbdocker $DOCKER_HUB_USER_ID/sbdocker:latest
      - docker push $DOCKER_HUB_USER_ID/sbdocker:$CIRCLE_SHA1
      - docker push $DOCKER_HUB_USER_ID/sbdocker:latest
